### ISSUE TITLE
getAAColours function lacks the color of amino acid 'B'

### ISSUE THREAD

**Issue by ugobananas** [KatyBrown/CIAlign#13]
Hi, the getAAColours() in the utilityFunctions.py lacks the colour annotation of 'B'. There are some 'B' residues in my MSA. Could you please add it into the script?

**Comment by KatyBrown** [comment]
Hi,

Sorry about that - we didn't include ambiguous amino acids.  We've just added them now so if you pull the latest commit it should work - they will show up in grey.

Please let us know if you have any other problems.

Katy
