### ISSUE TITLE
Bioconda

### ISSUE THREAD

**Issue by geboro** [KatyBrown/CIAlign#16]
Any plans of making CIAlign available through bioconda or bioconductor? conda and pip are engaging into a dependency war in my machine...

**Comment by KatyBrown** [comment]
Hi @geboro - we're working on it! I've had some problems getting it set up, possibly because of the intra-conda dependency war on my machine. If I can get a handle on it there will hopefully be a conda version of the next release. We don't have any plans for Bioconductor at the moment but it's a good thought for the future.

**Comment by dgslos** [comment]
Hi @geboro , I would recommend you to use a virtual environment in the mean time. https://docs.python.org/3/library/venv.html It will solve your dependencies problem I think. You can do something like this (note it will pull the latest changes, some might be in development):

```
cd /home/user/
python3 -m venv //home/user/.venv_cialign
source /home/user/.venv_cialign/bin/activate 
git clone https://github.com/KatyBrown/CIAlign.git 
mv CIAlign ./.venv_cialign 
cd .venv_cialign/CIAlign 
python3 setup.py install
```

Or with pip if it works for you:
```
cd /home/user/
python3 -m venv //home/user/.venv_cialign
source /home/user/.venv_cialign/bin/activate 
pip install CIAlign
```

To run it do:
```
#Activate the virtual environment
source /home/user/.venv_cialign/bin/activate

#Run CIalign
CIalign -h

#When finished, close the virtual enviroment
deactivate

```

Docker containers could also solve your issue. Hope it helps! :)

**Comment by KatyBrown** [comment]
Hi @geboro I realise it's been a while but CIAlign is now available via bioconda -  https://anaconda.org/bioconda/cialign. Thanks for your comment!
