### ISSUE TITLE
CIAlign influences aligment itself

### ISSUE THREAD

**Issue by dgslos** [KatyBrown/CIAlign#22]
Hi, 
Today I found CIAlign is changing my alignment in an inproper way. I have three sequences that are exactly the same (named number 1-3 in the bottom of the printscreen) except that one is longer than the other. I aligned it with mafft and they show up perfectly aligned:,-

![image](https://user-images.githubusercontent.com/65173064/105193859-455e3f00-5b39-11eb-9ba7-142bdaa4634e.png)

To remove the gaps only, I tried CIAlign with the keep_gapsonly = 0 option.
When I visually checked the result, the sequences are no longer well aligned.... Parts have been shifted:
![image](https://user-images.githubusercontent.com/65173064/105194356-c9b0c200-5b39-11eb-8b9b-8cb135d5030b.png)

Is it a bug or am I doing something wrong?

**Comment by KatyBrown** [comment]
Hi @dgslos
Thank you very much for letting us know - we'll look in to this. If you don't mind, please could you email the full alignment and the cleaned alignment to me (kab84 at cam.ac.uk), along with the full command which you used.  The keepgaps=0 option should only remove full columns and the alignment shouldn't change - so I need to check what's happening here.
Katy

**Comment by dgslos** [comment]
Solved, it was my mistake in the filenames! Thanks for digging in!

**Comment by KatyBrown** [comment]
Thanks!
