### ISSUE TITLE
keep_gaponly?

### ISSUE THREAD

**Issue by ollenordesjo** [KatyBrown/CIAlign#28]
Hello!

Quick q about the keep_gaponly option:

https://github.com/KatyBrown/CIAlign/blob/master/CIAlign/CIAlign.py#L115

Since it defaults to True, does it make sense to change the wording? remove_gaponly and default to False perhaps? 

Thanks!

**Comment by ollenordesjo** [comment]
Ah, I may have been mistaken, just running with default will actually remove gaponly right? In that case, maybe some tweaking can be done to show that the default is False?

**Comment by schnamo** [comment]
Hi! Thank you for altering us to this problem, it is indeed misleading.

By default, gap-only columns will be removed, however, if "--keep_gaponly" is added to the CIAlign call, internally remove_gaponly will be set to false and therefore gaponly columns won't be removed. I hope this makes sense!

**Comment by ollenordesjo** [comment]
Thanks, makes perfect sense now having looked at it again, and thanks for the clarification!
