### ISSUE TITLE
Let the user change the '--remove_insertions' percentage

### ISSUE THREAD

**Issue by lukaszsobala** [KatyBrown/CIAlign#40]
Hello,
Thanks for developing the software. I was wondering if it would be possible to let the user specify the minimum fraction of sequences to contain the insertions before they are removed, for example by adding a function "--remove_insertions_minperc". 50% seems a bit arbitrary.

**Comment by KatyBrown** [comment]
Hi @lukaszsobala, thanks for using CIAlign and for your suggestion. We have now added this functionality - you can use the --insertion_min_perc parameter to set the minimum proportion of sequences in which the insertion should appear. Please let us know if you have any problems with it.
See commits https://github.com/KatyBrown/CIAlign/commit/8aac6a3ff3e94ba4b56a5fc8a299b4ef6a007920 and https://github.com/KatyBrown/CIAlign/commit/905e6a77369ba494b4b24d14166b32cbeecb2aa5

**Comment by lukaszsobala** [comment]
Thank you!
