### ISSUE TITLE
Option for original sequence names in plots

### ISSUE THREAD

**Issue by PeterP-GH** [KatyBrown/CIAlign#67]
I would love to see an argument that allows to keep the original sequence names from the FASTA input for the --plot_input and --plot_output plots. Currently the plots only contain consecutive numbers as labels.
I hope for an argument, e.g. --plot_keep_names, which keeps the original names of the FASTA header. It doesn't matter if long names extend into the plot itself.

**Comment by KatyBrown** [comment]
Hi @PeterP-GH, good idea! I've (I think) added this as an option in https://github.com/KatyBrown/CIAlign/pull/68, it should be merged into the main branch soon and included in the next release. At the moment the font size is not adjustable so for large plots the names will overlap if the height is not sufficient.
Thanks!
